name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::${{secrets.TEST_SECRET}}"
      - name: echo a secret
        run: echo "your secret token is ${{secrets.TEST_SECRET}}"
